name       : dmd
version    : 2.080.1
release    : 9
source     :
    - git|https://github.com/dlang/dmd : v2.080.1
    - git|https://github.com/dlang/druntime : v2.080.1
    - git|https://github.com/dlang/phobos : v2.080.1
license    : BSL-1.0
component  : programming
summary    : Digital Mars D (DMD) is the reference compiler and standard library for the D programming language
description: |
    D is a systems programming language with C-like syntax and static typing. It combines efficiency, control and modeling power with safety and programmer productivity.
libsplit   : no
strip      : no
extract    : no
builddeps  :
    - dmd
optimize   :
    - lto
patterns   :
    - /usr/include/*
    - /usr/lib64/*
setup      : |
    cp -r $sources/dmd.git $workdir/dmd
    cp -r $sources/druntime.git $workdir/druntime
    cp -r $sources/phobos.git $workdir/phobos
build      : |
    %make -f posix.mak
    pushd $workdir/../druntime
        %make -f posix.mak DMD=$workdir/generated/linux/release/64/dmd
    popd
    pushd $workdir/../phobos
        %make -f posix.mak DMD=$workdir/generated/linux/release/64/dmd
    popd
install    : |
    install -Dm00755 $workdir/generated/linux/release/64/dmd $installdir/usr/bin/dmd
    install -dm00644 $installdir/usr/include/dlang/dmd
    cp -r $workdir/../phobos/{*.d,etc,std} $installdir/usr/include/dlang/dmd
    cp -r $workdir/../druntime/import/* $installdir/usr/include/dlang/dmd
    install -Dm00744 $workdir/../phobos/generated/linux/release/64/libphobos2.a $installdir/usr/lib64/libphobos2.a
    install -Dm00755 $workdir/../phobos/generated/linux/release/64/libphobos2.so $installdir/usr/lib64/libphobos2.so
    install -Dm00755 $workdir/../phobos/generated/linux/release/64/libphobos2.so.0.* $installdir/usr/lib64/
    install -Dm00644 $pkgfiles/dmd.conf $installdir/etc/dmd.conf
    install -dm00644 $installdir/usr/share/man/
    cp -r docs/man/* $installdir/usr/share/man/
