name       : dmd
version    : 2.071.2
release    : 2
source     :
    - git|https://github.com/dlang/dmd : v2.071.2
    - git|https://github.com/dlang/druntime : v2.071.2
    - git|https://github.com/dlang/phobos : v2.071.2
license    : Boost Software License 1.0
component  : programming
summary    : Compiler and standard library for the D programming language
description: |
    D is a systems programming language with C-like syntax and static typing. It combines efficiency, control and modeling power with safety and programmer productivity.
patterns   :
    - /usr/include/*
    - /usr/lib64/*
    - /usr/bin/*
    - /etc/*
    - /usr/share/man/*
libsplit   : no
builddeps  :
    - dmd
setup      : |
    cp -r $sources/druntime.git $workdir/druntime
    cp -r $sources/phobos.git $workdir/phobos
    SUBFOLDERS=$(ls $workdir)
    mkdir -p $workdir/stage1
    for SUBFOLDER in $SUBFOLDERS; do cp -R $workdir/$SUBFOLDER $workdir/stage1; done
build      : |
    export CXX_KIND="g++"
    cd $workdir/stage1
    %make -f posix.mak
    cd $workdir/stage1/druntime
    %make -f posix.mak DMD=$workdir/stage1/src/dmd
    cd $workdir/stage1/phobos
    %make -f posix.mak DMD=$workdir/stage1/src/dmd
    cd $workdir
    %make -f posix.mak DMD=$workdir/stage1/src/dmd
    cd $workdir/druntime
    %make -f posix.mak DMD=$workdir/src/dmd
    cd $workdir/phobos
    %make -f posix.mak DMD=$workdir/src/dmd
install    : |
    install -Dm755 $workdir/src/dmd $installdir/usr/bin/dmd
    install -dm644 $installdir/usr/include/dlang/dmd
    cp -r phobos/{*.d,etc,std} $installdir/usr/include/dlang/dmd
    cp -r druntime/import/* $installdir/usr/include/dlang/dmd
    install -Dm744 phobos/generated/linux/release/64/libphobos2.a $installdir/usr/lib64/libphobos2.a
    install -Dm755 phobos/generated/linux/release/64/libphobos2.so $installdir/usr/lib64/libphobos2.so
    install -Dm644 $pkgfiles/dmd.conf $installdir/etc/dmd.conf
    install -dm644 $installdir/usr/share/man/
    cp -r docs/man/* $installdir/usr/share/man/
